#!/bin/bash

#Debug Optionen
scripts/config --enable CONFIG_KGDB
scripts/config --enable CONFIG_GDB_SCRIPTS
scripts/config --disable CONFIG_DEBUG_INFO_REDUCED
scripts/config --enable CONFIG_DEBUG_KERNEL

#notwendig, damit die init Datei erkannt und entpackt wird
scripts/config --enable CONFIG_RD_GZIP
scripts/config --enable CONFIG_INITRAMFS_SOURCE
scripts/config --enable CONFIG_BLK_DEV_INITRD
scripts/config --enable CONFIG_RD_RAMFS
#Deaktiviere THP
scripts/config --disable CONFIG_TRANSPARENT_HUGEPAGE
#Aktiviere serielle Schnittstellen, um qemu im nographic modus zu nutzen
scripts/config --enable CONFIG_SERIAL_8250
scripts/config --enable CONFIG_SERIAL_8250_CONSOLE


make olddefconfig


